import 'package:flutter/material.dart';
import 'package:redresq_app/components/my_colors.dart';

class TsunamiGeneralInformation extends StatelessWidget {
  const TsunamiGeneralInformation({Key? key}) : super(key: key);

  TextSpan _buildHeading(String text) {
    return TextSpan(
      text: '\n' + text + '\n',
      style: TextStyle(
        fontWeight: FontWeight.bold,
        fontSize: 25,
        color: Colors.black,
      ),
    );
  }

  TextSpan _buildSubHeading(String text) {
    return TextSpan(
      text: '\n' + text + '\n',
      style: TextStyle(
        fontWeight: FontWeight.bold,
        fontSize: 20,
        color: Colors.black,
      ),
    );
  }

  TextSpan _buildText(String text) {
    return TextSpan(
      text: '\n' + text + '\n',
      style: TextStyle(
        fontSize: 14,
        color: Colors.black,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          SizedBox(
            height: 20,
          ),
          Flexible(
            flex: 1,
            child: Card(
              margin: const EdgeInsets.symmetric(
                horizontal: 20,
                vertical: 10,
              ),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(20),
              ),
              elevation: 3,
              child: Padding(
                padding: const EdgeInsets.only(
                  left: 16,
                  bottom: 16,
                  right: 16,
                ),
                child: ListView(children: [
                  RichText(
                    textAlign: TextAlign.left,
                    text: TextSpan(
                      style: TextStyle(
                          fontWeight: FontWeight.normal,
                          fontSize: 14,
                          fontStyle: FontStyle.normal,
                          color: myBlackColor),
                      children: [
                        _buildHeading('General Information'),
                        _buildSubHeading('What is a tsunami?'),
                        _buildText(
                            "A large wave that is caused by movements in Earth's outer layer, or crust, which move ocean water"),
                        _buildSubHeading('Characteristics of a Tsunami'),
                        _buildText(
                            "- A tsunami travels outward from the source region as a series of waves.\n\n"
                            "- Its speed and height depend upon the depth of the water.\n\n"
                            "- In the deep ocean, tsunamis travel between 500 and 1000 km/h.\n\n"
                            "- Tsunamis have periods that range between a couple of minutes to as much as an hour.\n\n"
                            "- Damage and destruction are caused by three factors: inundation, wave impact on structures, and erosion.\n\n"
                            "- Secondary damage is common"),
                        _buildSubHeading('Historical Tsunami'),
                        _buildText(
                            "A tsunami documented to occur through eyewitnesses or instrumental observation within the historical record."),
                        _buildSubHeading('Local Tsunami'),
                        _buildText(
                            "A local tsunami is a tsunami that originates from within 200 km of the coast or within 1 hour tsunami travel time. "
                            "It is usually caused by an earthquake but can also be caused by a landslide or a volcanic eruption. "
                            "Local tsunamis cause 90% of tsunami casualties."),
                        _buildSubHeading('Microtsunami'),
                        _buildText(
                            "A tsunami of such small amplitude that it is not easily detected visually."),
                        _buildSubHeading('Ocean-wide Tsunami'),
                        _buildText(
                            "A tsunami that is capable of widespread destruction, not only in the immediate region of its generation but across an entire ocean. "
                            "All ocean-wide tsunamis have been generated by major earthquakes. Synonym for teletsunami or distant Tsunami"),
                        _buildSubHeading('Regional Tsunami'),
                        _buildText(
                            "A tsunami capable of destruction in a particular geographic region, generally within 1,000 km or 1-3 hours tsunami travel time from its source."),
                        _buildSubHeading('Teletsunami'),
                        _buildText(
                            "A tsunami originating from a far-away source, generally more than 1,000 km or more than 3 hours tsunami travel time from its source. "
                            "More devastating than the Regional Tsunami, however, it is less frequent"),
                        _buildSubHeading('Tsunami Meaning'),
                        _buildText(
                            "Japanese term meaning wave (“nami”) in a harbor (“tsu”). A series of traveling waves of extremely long length and period, usually generated by disturbances associated with earthquakes occurring below or near the ocean floor."),
                        _buildSubHeading('The Misleading Term Tidal Waves'),
                        _buildText(
                            "The popular term tidal waves is entirely misleading as tsunamis have nothing in common with tides."),
                      ],
                    ),
                  ),
                ]),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
